### PR TITLE
Fixed so the randomdanktimes and the normal danktimes no longer overlap #65

### PR DESCRIPTION
**Pull request by WouterVanmulken**
It now checks if the danktimes are already added before adding them so they no longer overlap.

### CODE REVIEW

**Comment by WouterVanmulken** [comment]
I would like to make a unit test for commit [1](https://github.com/Agadar/DankTimesBot/pull/68/commits/5f9e5f431ab3ef5cb57aa083575a1d0262025063), although i'm not entirely sure how. And i'm not entirely sure if commit [2](https://github.com/Agadar/DankTimesBot/pull/68/commits/463f240eab491eb8d0ed334c99dbb1fae979ac88) will work so this might also still need a unit test.

**Comment by Lerke** [comment]
Thinking about this, I see two 'easy' ways to write unit tests for #68. You could use some mocking framework to mock out Math.Random to just return a constant or predictable stream of values. Alternatively, you could re-architecture Chats such that they are no longer responsible for generating 'random' DankTimes. In this scenario, I'd imagine getting rid of `generateRandomDankTimes()` entirely and letting main just generate a sequence of 'random' danktimes. Chat would then only have to check if these 'random' times are already present and figure out a way to deal with that.

Let me know what you think.

**Comment by WouterVanmulken** [comment]
I think i'm going to try to mock it, it might be worth rewriting at some point. So i'm going to look into it.

**Comment by Agadar** [comment]
Is this still being worked on?

**Comment by WouterVanmulken** [comment]
Honestly...no.  I currently don't have the time to finish it either. I started on it but never finished it.

**Comment by Agadar** [comment]
Alright, closing it for now then.

**Pull request closed without merging**
